export const ANDROID_VERSION_NAMES: Record<string, string> = {
  "36.1": 'Android 16.0 ("Baklava")',
  "36": 'Android 16.0 ("Baklava")',
  "35": 'Android 15.0 ("VanillaIceCream")',
  "34": 'Android 14.0 ("UpsideDownCake")',
  "33": 'Android 13.0 ("Tiramisu")',
  "32": 'Android 12L ("Snow Cone v2")',
  "31": 'Android 12.0 ("Snow Cone")',
  "30": 'Android 11.0 ("Red Velvet Cake")',
  "29": 'Android 10.0 ("Quince Tart")',
  "28": 'Android 9.0 ("Pie")',
  "27": 'Android 8.1 ("Oreo")',
  "26": 'Android 8.0 ("Oreo")',
  "25": 'Android 7.1 ("Nougat")',
  "24": 'Android 7.0 ("Nougat")',
  "23": 'Android 6.0 ("Marshmallow")',
  "22": 'Android 5.1 ("Lollipop")',
  "21": 'Android 5.0 ("Lollipop")',
  "20": 'Android 4.4W ("KitKat Wear")',
  "19": 'Android 4.4 ("KitKat")',
  "18": 'Android 4.3 ("Jelly Bean")',
  "17": 'Android 4.2 ("Jelly Bean")',
  "16": 'Android 4.1 ("Jelly Bean")',
  "15": 'Android 4.0.3 ("Ice Cream Sandwich")',
  "14": 'Android 4.0 ("Ice Cream Sandwich")',
  "13": 'Android 3.2 ("Honeycomb")',
  "12": 'Android 3.1 ("Honeycomb")',
  "11": 'Android 3.0 ("Honeycomb")',
  "10": 'Android 2.3.3 ("Gingerbread")',
  "9": 'Android 2.3 ("Gingerbread")',
  "8": 'Android 2.2 ("Froyo")',
  "7": 'Android 2.1 ("Eclair")',
  Baklava: "Android Baklava Preview",
  CinnamonBun: "Android CinnamonBun Preview",
  CANARY: "Android CANARY Preview",
  UpsideDownCake: "Android UpsideDownCake Preview",
};
